# Basic
name:               "Pixel's Translations"

# jekyll-seo-tag
url:                "//pixelzerg.com/translation/"
author:             "pixelzerg"
twitter:
  username:         "pixelzerg"

# URL
baseurl:            "/translation"
permalink:          /:categories/:title/


# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    remote:         false
    localpath:      "about"

# Sass
sass:
  style:            :compressed

# collections:
collections:
  category:
    output: true

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         artists
    values:
      layout:       "artist"

plugins:
  - jekyll-seo-tag
