# Basic
name:               "Pixel's Translations"

# jekyll-seo-tag
url:                "//pixelzerg.com/translation/"
author:             "pixelzerg"
twitter:
  username:         "pixelzerg"

# URL
baseurl:            "/translation"
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    remote:         false
    localpath:      "about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
