# Basic
name:               "Pixel's Translations"

# jekyll-seo-tag
url:                "//pixelzerg.com/translation/"
author:             "pixelzerg"
twitter:
  username:         "pixelzerg"

# URL
baseurl:            "/translation"
permalink:          /:categories/:title/

markdown:           kramdown

defaults:
  -
    scope:
      path:         ""
      type:         artists
    values:
      layout:       "artist"

plugins:
  - jekyll-seo-tag

sass:
  sass_dir: res/
  style: compressed
