# Basic
name:               "Pixel's Translations"

# jekyll-seo-tag
url:                "//pixelchai.com/translation/"
author:             "pixelchai"
twitter:
  username:         "pixelchai"

# URL
baseurl:            "/translation"
permalink:          /:categories/:title/

markdown:           kramdown

defaults:
  -
    scope:
      path:         ""
      type:         artists
    values:
      layout:       "artist"

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

sass:
  sass_dir: res/
  style: compressed
